name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: checkout baserom
      uses: actions/checkout@v2
      with:
        repository: mkst/conker-private
        token: ${{ secrets.PRIVATE_REPO_ACCESS }}
        path: baserom
    - name: copy in baserom
      run: mv baserom/baserom.us.z64 .
    # main
    - name: make extract
      uses: docker://docker.io/markstreet/conker:latest
      with: 
        args: make extract
    - name: make
      uses: docker://docker.io/markstreet/conker:latest
      with: 
        args: make --jobs
    - name: make decompress
      uses: docker://docker.io/markstreet/conker:latest
      with: 
        args: make decompress
    # chunk 0
    - name: make extract (chunk0)
      uses: docker://docker.io/markstreet/conker:latest
      with: 
        args: cd chunk0 && make extract
    - name: make (chunk0)
      uses: docker://docker.io/markstreet/conker:latest
      with: 
        args: sh -c "cd chunk0 && make --jobs"
    - name: make split (chunk0)
      uses: docker://docker.io/markstreet/conker:latest
      with: 
        args: sh -c "cd chunk0 && make split"
      
