name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: markstreet/conker:latest
    steps:
    - name: print pwd
      run: pwd
    - name: checkout this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: whats new
      run: ls -al
    - name: checkout baserom
      uses: actions/checkout@v2
      with:
        clean: no
        repository: mkst/conker-private
        token: ${{ secrets.PRIVATE_REPO_ACCESS }}
    - name: how about now
      run: ls -al
    # main
    - name: make extract
      run: make extract
    - name: make
      run: make
    - name: make decompress
      run: make decompress
    # chunk 0
    - name: make extract (chunk0)
      run: make extract     
      working-directory: conker/chunk0/
    - name: make (chunk0)
      run: make 
      working-directory: conker/chunk0/
      
